### ISSUE TITLE
Patching mainTemplate.gradle should be optional

### ISSUE THREAD

**Issue by jsaade** [googlesamples/unity-jar-resolver#216]
Patching is being done automatically, some problems:
- When using multidex, it is overwritting some configuration that I specifically want.
- It is writing some configruation twice (ex: allprojects { ... )
- trying to use google() in repositories is being deleted automatically

I am not sure what advantages does patching offers, but I am unable to build when it is enabled.
I have rolled back to pre-105 release for it to work.

**Comment by wisestump** [comment]
I ran into a problem with the auto-patching. For some reason when using patched gradle template instead of libraries being resolved and downloaded by jar resolver itself, my application crashes in a certain case.
When I use firebase 6.0.0 (dynamic links), OneSignal 2.7.9, Facebook 7.15.1 and resolver 1.2.111 with custom gradle template I get a crash upon receiving push notification via OneSignal with this message:

```
05-15 19:23:22.381: E/AndroidRuntime(27814): Caused by: java.lang.IllegalAccessError: com.google.firebase.messaging.FirebaseMessagingService
05-15 19:23:22.381: E/AndroidRuntime(27814): 	at dalvik.system.DexFile.defineClassNative(Native Method)
05-15 19:23:22.381: E/AndroidRuntime(27814): 	at dalvik.system.DexFile.defineClass(DexFile.java:226)
05-15 19:23:22.381: E/AndroidRuntime(27814): 	at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
05-15 19:23:22.381: E/AndroidRuntime(27814): 	at dalvik.system.DexPathList.findClass(DexPathList.java:338)
05-15 19:23:22.381: E/AndroidRuntime(27814): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
05-15 19:23:22.381: E/AndroidRuntime(27814): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
05-15 19:23:22.381: E/AndroidRuntime(27814): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
05-15 19:23:22.381: E/AndroidRuntime(27814): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3838)
05-15 19:23:22.381: E/AndroidRuntime(27814): 	at android.app.ActivityThread.access$2100(ActivityThread.java:229)
05-15 19:23:22.381: E/AndroidRuntime(27814): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1909)
05-15 19:23:22.381: E/AndroidRuntime(27814): 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-15 19:23:22.381: E/AndroidRuntime(27814): 	at android.os.Looper.loop(Looper.java:148)
05-15 19:23:22.381: E/AndroidRuntime(27814): 	at android.app.ActivityThread.main(ActivityThread.java:7406)
05-15 19:23:22.381: E/AndroidRuntime(27814): 	at java.lang.reflect.Method.invoke(Native Method)
05-15 19:23:22.381: E/AndroidRuntime(27814): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
05-15 19:23:22.381: E/AndroidRuntime(27814): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

On some devices the error is different:
```
Caused by: java.lang.IllegalAccessError: Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible
```

But the issue appears only when using patched gradle file. At this point I can't get rid of my custom gradle template and forced to use the older resolver version.

**Comment by kobyle69** [comment]
@jsaade I'm having the same problem.
Also added an 'hack' solution, take a look at:
https://github.com/googlesamples/unity-jar-resolver/issues/210

**Comment by stewartmiles** [comment]
Moving the feature request to #210
