### ISSUE TITLE
.xcworkspace isn't generated. Failed to install cocoapods for current user

### ISSUE THREAD

**Issue by HamzaMunir** [googlesamples/unity-jar-resolver#299]
I am using latest resolver. It was working fine until I updated MacOS to Catalina 10.15.1
Using Unity 2019.2.5f1 
Now it gives me this error

 ```
Failed to install CocoaPods for the current user.

It will not be possible to install Cocoapods in the generated Xcode project which will result in link errors when building your application.

For more information see:
  https://guides.cocoapods.org/using/getting-started.html


'/Users/hamzamunir/.gem/ruby/2.6.0/bin/pod setup' failed with code (1):


/Users/hamzamunir/.gem/ruby/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:118:in `git_version': Failed to extract git version from `git --version` ("xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun\n") (RuntimeError)
	from /Users/hamzamunir/.gem/ruby/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:130:in `verify_minimum_git_version!'
	from /Users/hamzamunir/.gem/ruby/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:49:in `run'
	from /Users/hamzamunir/.gem/ruby/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
	from /Users/hamzamunir/.gem/ruby/2.6.0/bin/pod:23:in `load'
	from /Users/hamzamunir/.gem/ruby/2.6.0/bin/pod:23:in `<main>'
```

**Comment by stewartmiles** [comment]
@HamzaMunir assuming you haven't figured out the solution already, the problem is described in the error message:
`xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun\n") (RuntimeError)`

quick Google search turns up:
https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-update-xcrun-error-invalid-active-developer-pa

which seems reasonable.
