### ISSUE TITLE
java.lang.ClassNotFoundException on Android

### ISSUE THREAD

**Issue by viniciusguerra** [googlesamples/unity-jar-resolver#76]
I got in contact with Firebase Support after having some problems with Firebase and Google Play Games for Unity.
Both plugins declared repeated classes and thus were not able to convert into dex-format successfully when building.
Then Unity Jar Resolver was updated and I no longer had problems when building, but had the following problem that is detailed in the [attached log](https://github.com/googlesamples/unity-jar-resolver/files/1360262/log.txt) that was recovered from LogCat.
Thanks for the support.

**Comment by stewartmiles** [comment]
@claywilkinson FYI

@viniciusguerra while I'm happy to respond, I would like to mention that we're not general support for all plugins that use the Play Services Resolver.

That said, now I've looked at your log the key lines are here:

```
09-27 18:51:52.753: W/Unity(22228): *** [Play Games Plugin DLL] 09/27/17 18:51:52 -03:00 ERROR: Exception launching token request: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
09-27 18:51:52.753: W/Unity(22228): UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
09-27 18:51:52.753: W/Unity(22228): UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
09-27 18:51:52.753: W/Unity(22228): UnityEngine.Logger:Log(LogType, Object)
09-27 18:51:52.753: W/Unity(22228): UnityEngine.Debug:LogWarning(Object)
09-27 18:51:52.753: W/Unity(22228): GooglePlayGames.OurUtils.<e>c__AnonStorey2:<>m__0() (at C:\Development\Projects\Promob\Assets\GooglePlayGames\OurUtils\Logger.cs:77)
09-27 18:51:52.753: W/Unity(22228): GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at C:\Development\Projects\Promob\Assets\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:135)
09-27 18:51:52.753: W/Unity(22228):  
09-27 18:51:52.753: W/Unity(22228): (Filename: C Line: 0)
09-27 18:51:52.761: W/Unity(22228): *** [Play Games Plugin DLL] 09/27/17 18:51:52 -03:00 ERROR: UnityEngine.AndroidJavaException: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
09-27 18:51:52.761: W/Unity(22228): java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
09-27 18:51:52.761: W/Unity(22228): 	at java.lang.Class.classForName(Native Method)
09-27 18:51:52.761: W/Unity(22228): 	at java.lang.Class.forName(Class.java:309)
09-27 18:51:52.761: W/Unity(22228): 	at java.lang.Class.forName(Class.java:273)
09-27 18:51:52.761: W/Unity(22228): 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
09-27 18:51:52.761: W/Unity(22228): 	at com.unity3d.player.UnityPlayer.c(Unknown Source)
09-27 18:51:52.761: W/Unity(22228): 	at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source)
09-27 18:51:52.761: W/Unity(22228): 	at android.os.Handler.dispatchMessage(Handler.java:98)
09-27 18:51:52.761: W/Unity(22228): 	at android.os.Looper.loop(Looper.java:135)
09-27 18:51:52.761: W/Unity(22228): 	at com.unity3d.player.UnityPlayer$c.run(Unknown Source)
09-27 18:51:52.761: W/Unity(22228): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.games.bridge.TokenFragment" on path: DexPathList[[zip file "/data/app/com.Tecgraf.Promob-2/base.apk"],nativeLibraryDirectories=[/data/app/com.Tecgraf.Promob-2/lib/arm, /vendor/lib, /system/lib]]
09-27 18:51:52.761: W/Unity(22228): 	at dalvik.system.BaseDexClassLoader.
09-27 18:52:27.285: I/Unity(22228): onPause
09-27 18:52:27.495: D/Unity(22228): Sensor :        Accelerometer ( 1) ; 0.039227 / 0.00s ; MPL Accelerometer / Invensense 
09-27 18:52:27.512: I/Unity(22228): windowFocusChanged: false
09-27 18:52:27.575: D/Unity(22228): SetWindow 0 0x0
```

In particular, the class `com.google.games.bridge.TokenFragment` appears to be missing from your APK (see https://github.com/playgameservices/play-games-plugin-for-unity/tree/master/source/SupportLib) .  Is it possible you removed the Google Play Games AAR from `Assets/Plugins/Android/play-games-plugin-support.aar` ?

@claywilkinson it may be worth moving this file into a local maven repo in the plugin (see Firebase) that is managed by the Android Resolver rather than distributing it in `Assets/Plugins/Android` to avoid this sort of thing in future.

Cheers,
Stewart

**Comment by stewartmiles** [comment]
@viniciusguerra I'll assume my response resolved your problem.  Please let us know if you have any other issues.
