### ISSUE TITLE
No such file or directory in Android Prebuild with Gradle

### ISSUE THREAD

**Issue by kenglou** [googlesamples/unity-jar-resolver#77]
Here are my setup:
1. Unity3d 5.6.3p4
2. Jar Resolver 1.2.54.0 (I had tried to updated it but seems not working)
3. PlayGameUnityPlugin 0.9.41
4. Mac OS Sierra 10.12.6

Below occurs when i wanted to resolve client in Android Build.
```
Error somewhere in the process of creating the gradle build, executing it, and copying the outputs.
This will break dependency resolution and your build will not run.
See the output below for possible gradle build errors. The most likely cases are: an invalid bundleID (which you can correct in the Android Player Settings), or a failure to determine the Android SDK platform and build tools verison (you can verify that you have a valid android SDK path in the Unity preferences.
If you're not able to diagnose the error, please report a bug at: https://github.com/googlesamples/unity-jar-resolver/issuesA possible work-around is to turn off the "Gradle Prebuild" from the Jar Resolver Settings.

Error (1):
Traceback (most recent call last):
  File "Temp/PlayServicesResolverGradlePrebuild/generate_gradle_prebuild.py", line 476, in <module>
    sys.exit(main())
  File "Temp/PlayServicesResolverGradlePrebuild/generate_gradle_prebuild.py", line 468, in main
    generate_gradle_build(build_path, jsobj)
  File "Temp/PlayServicesResolverGradlePrebuild/generate_gradle_prebuild.py", line 215, in generate_gradle_build
    ignore=shutil.ignore_patterns("*.meta"))
  File "Temp/PlayServicesResolverGradlePrebuild/generate_gradle_prebuild.py", line 76, in merge_dir_tree
    paths = os.listdir(src)
OSError: [Errno 2] No such file or directory: 'https://maven.google.com'

UnityEngine.Debug:LogError(Object)
GooglePlayServices.<RunGenGradleScript>c__AnonStoreyE:<>m__11(Result)
GooglePlayServices.ProgressReporter:Update(CommandLineDialog)
```

Tested with different Wifi and I actually has no proxy setup from my router(all default). 
And if i do a GooglePlayGames Setup, it seems actually run the scripts and stucks forever (I had wait for 1 hour ++ but it still in the progress of importing installed AndroidPackages)

Here are my setup for the JAR Resolver:
![screen shot 2017-10-06 at 2 16 46 pm](https://user-images.githubusercontent.com/4876665/31265358-07605a04-aaa1-11e7-854c-6335b7094048.png)

Any helps would be great!
Thank you.

**Comment by Bestlis** [comment]
Did you solve this problem?

**Comment by stewartmiles** [comment]
We removed this experimental feature in aa1a6b8e71ccf99bdf1f935851e9242a39d88bd4 .
