### ISSUE TITLE
Prebuild with Gradle in 1.2.59.0: Malformed \uxxxx encoding.

### ISSUE THREAD

**Issue by yuriy-universal-ivanov** [googlesamples/unity-jar-resolver#92]
Hi,

Unity 2017.2.0f3, Windows 10.
There is an issue when turning on Prebuild with Gradle (Android):

```
Error somewhere in the process of creating the gradle build, executing it, and copying the outputs.
This will break dependency resolution and your build will not run.
See the output below for possible gradle build errors. The most likely cases are: an invalid bundleID (which you can correct in the Android Player Settings), or a failure to determine the Android SDK platform and build tools verison (you can verify that you have a valid android SDK path in the Unity preferences.
If you're not able to diagnose the error, please report a bug at: https://github.com/googlesamples/unity-jar-resolver/issuesA possible work-around is to turn off the "Gradle Prebuild" from the Jar Resolver Settings.

Error (-1):

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\u-n-i\Documents\projects\utnotifications\unity\Temp\GenGradle\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating root project 'GenGradle'.
> Failed to apply plugin [id 'com.android.application']
   > Malformed \uxxxx encoding.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Traceback (most recent call last):
  File "<string>", line 475, in <module>
  File "<string>", line 468, in main
  File "<string>", line 260, in execute_gradle_build
RuntimeError: Failed running gradle build
generate_gradle_prebuild returned -1

UnityEngine.Debug:LogError(Object)
GooglePlayServices.<RunGenGradleScript>c__AnonStoreyE:<>m__11(Result)
GooglePlayServices.ProgressReporter:Update(CommandLineDialog)
GooglePlayServices.CommandLineDialog:Update()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
```

Thank you in advance for any assistance,
Best regards,
Yuriy

**Comment by stewartmiles** [comment]
We removed this experimental feature in aa1a6b8e71ccf99bdf1f935851e9242a39d88bd4 .
